begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agencies (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  slug text not null unique,
  logo_path text,
  brand_color text not null default '#6750A4',
  timezone text not null default 'America/New_York',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agency_members (
  agency_id uuid not null references public.agencies(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member')),
  created_at timestamptz not null default now(),
  primary key (agency_id, user_id)
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  name text not null,
  email text,
  website text,
  status text not null default 'active' check (status in ('active','paused','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.google_connections (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade unique,
  google_email text,
  encrypted_refresh_token text not null,
  token_iv text not null,
  token_tag text not null,
  scope text not null,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ad_accounts (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  customer_id text not null,
  descriptive_name text not null,
  currency_code text not null default 'USD',
  timezone text not null default 'America/New_York',
  status text not null default 'enabled',
  last_synced_at timestamptz,
  sync_error text,
  created_at timestamptz not null default now(),
  unique (agency_id, customer_id)
);

create table if not exists public.campaign_metrics (
  id bigint generated by default as identity primary key,
  agency_id uuid not null references public.agencies(id) on delete cascade,
  ad_account_id uuid not null references public.ad_accounts(id) on delete cascade,
  campaign_id text not null,
  campaign_name text not null,
  campaign_status text not null default 'UNKNOWN',
  metric_date date not null,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  cost_micros bigint not null default 0,
  conversions numeric(14,4) not null default 0,
  conversion_value numeric(16,4) not null default 0,
  synced_at timestamptz not null default now(),
  unique (ad_account_id, campaign_id, metric_date)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  ad_account_id uuid references public.ad_accounts(id) on delete set null,
  name text not null,
  period_start date not null,
  period_end date not null,
  status text not null default 'draft' check (status in ('draft','generating','ready','failed')),
  blob_path text,
  snapshot jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.report_shares (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  agency_id uuid not null references public.agencies(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.report_schedules (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  ad_account_id uuid references public.ad_accounts(id) on delete cascade,
  cadence text not null check (cadence in ('weekly','monthly')),
  recipient_email text not null,
  timezone text not null default 'America/New_York',
  next_run_at timestamptz not null,
  active boolean not null default true,
  workflow_run_id text,
  created_at timestamptz not null default now()
);

create index if not exists clients_agency_idx on public.clients(agency_id);
create index if not exists ad_accounts_agency_idx on public.ad_accounts(agency_id);
create index if not exists campaign_metrics_lookup_idx on public.campaign_metrics(agency_id, ad_account_id, metric_date desc);
create index if not exists reports_agency_idx on public.reports(agency_id, created_at desc);
create index if not exists schedules_next_run_idx on public.report_schedules(next_run_at) where active;

alter table public.profiles enable row level security;
alter table public.agencies enable row level security;
alter table public.agency_members enable row level security;
alter table public.clients enable row level security;
alter table public.google_connections enable row level security;
alter table public.ad_accounts enable row level security;
alter table public.campaign_metrics enable row level security;
alter table public.reports enable row level security;
alter table public.report_shares enable row level security;
alter table public.report_schedules enable row level security;

create or replace function public.is_agency_member(target_agency_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.agency_members
    where agency_id = target_agency_id and user_id = (select auth.uid())
  ) or exists (
    select 1 from public.agencies
    where id = target_agency_id and owner_id = (select auth.uid())
  );
$$;
revoke all on function public.is_agency_member(uuid) from public;
grant execute on function public.is_agency_member(uuid) to authenticated;

create or replace function public.is_agency_admin(target_agency_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.agency_members
    where agency_id = target_agency_id and user_id = (select auth.uid()) and role in ('owner','admin')
  ) or exists (
    select 1 from public.agencies
    where id = target_agency_id and owner_id = (select auth.uid())
  );
$$;
revoke all on function public.is_agency_admin(uuid) from public;
grant execute on function public.is_agency_admin(uuid) to authenticated;

create policy profiles_own on public.profiles for all to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy agencies_select on public.agencies for select to authenticated using (public.is_agency_member(id));
create policy agencies_insert on public.agencies for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy agencies_update on public.agencies for update to authenticated using (public.is_agency_admin(id)) with check (public.is_agency_admin(id));
create policy agencies_delete on public.agencies for delete to authenticated using ((select auth.uid()) = owner_id);
create policy members_select on public.agency_members for select to authenticated using (public.is_agency_member(agency_id));
create policy members_insert on public.agency_members for insert to authenticated with check (public.is_agency_admin(agency_id));
create policy members_update on public.agency_members for update to authenticated using (public.is_agency_admin(agency_id)) with check (public.is_agency_admin(agency_id));
create policy members_delete on public.agency_members for delete to authenticated using (public.is_agency_admin(agency_id));
create policy clients_access on public.clients for all to authenticated using (public.is_agency_member(agency_id)) with check (public.is_agency_member(agency_id));
create policy connections_access on public.google_connections for all to authenticated using (public.is_agency_admin(agency_id)) with check (public.is_agency_admin(agency_id));
create policy accounts_access on public.ad_accounts for all to authenticated using (public.is_agency_member(agency_id)) with check (public.is_agency_member(agency_id));
create policy metrics_access on public.campaign_metrics for select to authenticated using (public.is_agency_member(agency_id));
create policy reports_access on public.reports for all to authenticated using (public.is_agency_member(agency_id)) with check (public.is_agency_member(agency_id) and created_by = (select auth.uid()));
create policy shares_access on public.report_shares for all to authenticated using (public.is_agency_member(agency_id)) with check (public.is_agency_member(agency_id));
create policy schedules_access on public.report_schedules for all to authenticated using (public.is_agency_member(agency_id)) with check (public.is_agency_member(agency_id));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;
revoke all on function public.handle_new_user() from public;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.create_workspace(workspace_name text, workspace_slug text)
returns table(id uuid, name text, brand_color text, timezone text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := (select auth.uid());
  agency_row public.agencies%rowtype;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  select a.* into agency_row
  from public.agencies a
  where a.owner_id = current_user_id
  order by a.created_at
  limit 1;

  if agency_row.id is null then
    insert into public.agencies (owner_id, name, slug)
    values (current_user_id, workspace_name, workspace_slug)
    returning * into agency_row;
  end if;

  insert into public.agency_members (agency_id, user_id, role)
  values (agency_row.id, current_user_id, 'owner')
  on conflict (agency_id, user_id) do update set role = 'owner';

  return query
  select agency_row.id, agency_row.name, agency_row.brand_color, agency_row.timezone;
end;
$$;
revoke all on function public.create_workspace(text, text) from public;
revoke all on function public.create_workspace(text, text) from anon;
grant execute on function public.create_workspace(text, text) to authenticated;

commit;
