'use client'

import { FormEvent, useMemo, useState } from 'react'
import useSWR from 'swr'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'

type Data = { agency: { id: string; name: string }; user: { email?: string; name?: string }; clients: Array<{ id: string; name: string; email?: string; status: string }>; accounts: Array<{ id: string; client_id?: string; descriptive_name: string; customer_id: string; currency_code: string; last_synced_at?: string }>; metrics: Array<{ campaign_id: string; campaign_name: string; metric_date: string; impressions: number; clicks: number; cost_micros: number; conversions: number }>; reports: Array<{ id: string; name: string; status: string; period_start: string; period_end: string; client_id: string }>; connection?: { google_email?: string; connected_at: string } }
const fetcher = (url: string) => fetch(url).then(async r => { if (!r.ok) throw new Error('Request failed'); return r.json() })
const nav = [['overview','dashboard','Overview'], ['clients','groups','Clients'], ['campaigns','ads_click','Campaigns'], ['reports','description','Reports'], ['settings','settings','Settings']]

export function Dashboard() {
  const { data, error, isLoading, mutate } = useSWR<Data>('/api/dashboard', fetcher)
  const [view, setView] = useState('overview')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const totals = useMemo(() => (data?.metrics ?? []).reduce((a, row) => ({ impressions: a.impressions + Number(row.impressions), clicks: a.clicks + Number(row.clicks), spend: a.spend + Number(row.cost_micros) / 1_000_000, conversions: a.conversions + Number(row.conversions) }), { impressions: 0, clicks: 0, spend: 0, conversions: 0 }), [data])
  const chart = useMemo(() => { const dates = new Map<string, { date: string; spend: number; clicks: number }>(); for (const row of data?.metrics ?? []) { const point = dates.get(row.metric_date) ?? { date: row.metric_date.slice(5), spend: 0, clicks: 0 }; point.spend += Number(row.cost_micros) / 1_000_000; point.clicks += Number(row.clicks); dates.set(row.metric_date, point) } return [...dates.values()] }, [data])
  const campaigns = useMemo(() => { const map = new Map<string, { name: string; clicks: number; spend: number; conversions: number }>(); for (const row of data?.metrics ?? []) { const item = map.get(row.campaign_id) ?? { name: row.campaign_name, clicks: 0, spend: 0, conversions: 0 }; item.clicks += Number(row.clicks); item.spend += Number(row.cost_micros) / 1_000_000; item.conversions += Number(row.conversions); map.set(row.campaign_id, item) } return [...map.values()].sort((a,b) => b.spend-a.spend) }, [data])

  async function createClient(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch('/api/clients', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), email: form.get('email') }) }); const result = await response.json(); setNotice(response.ok ? 'Client added.' : result.error); if (response.ok) { event.currentTarget.reset(); await mutate() } setBusy(false) }
  async function syncAds() { setBusy(true); setNotice('Syncing the last 30 days…'); const response = await fetch('/api/google/sync', { method: 'POST' }); const result = await response.json(); setNotice(response.ok ? `Synced ${result.synced} campaign rows.` : result.error); if (response.ok) await mutate(); setBusy(false) }
  async function generateReport(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!data?.clients[0] || !data.accounts[0]) return; setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch('/api/reports', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ clientId: form.get('clientId'), accountId: form.get('accountId'), start: form.get('start'), end: form.get('end') }) }); const result = await response.json(); setNotice(response.ok ? 'Your PDF report is ready.' : result.error); if (response.ok) await mutate(); setBusy(false) }
  async function signOut() { await createSupabaseBrowserClient().auth.signOut(); window.location.assign('/auth/login') }

  if (isLoading) return <main className="loading-state"><md-circular-progress indeterminate /><p>Preparing your workspace…</p></main>
  if (error || !data) return <main className="loading-state"><h1>We could not load your workspace.</h1><button className="filled-button" onClick={() => mutate()}>Try again</button></main>

  return <div className="app-shell">
    <aside className="side-nav">
      <div className="brand-lockup"><span className="brand-mark"><span className="material-symbols-outlined">query_stats</span></span><strong>AdPulse</strong></div>
      <nav aria-label="Primary navigation">{nav.map(([id, icon, label]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => setView(id)}><span className="material-symbols-outlined">{icon}</span><span>{label}</span></button>)}</nav>
      <div className="agency-chip"><span>{data.agency.name.slice(0, 1)}</span><div><strong>{data.agency.name}</strong><small>{data.user.email}</small></div></div>
    </aside>
    <main className="app-main">
      <header className="topbar"><div><p className="eyebrow">AGENCY WORKSPACE</p><h1 className="md-typescale-headline-medium">{nav.find(n => n[0] === view)?.[2]}</h1></div><div className="top-actions"><button className="icon-button" aria-label="Refresh data" onClick={() => mutate()}><span className="material-symbols-outlined">refresh</span></button><button className="avatar-button" aria-label="Account menu" onClick={signOut}>{(data.user.name || data.user.email || 'A').slice(0,1).toUpperCase()}</button></div></header>
      {notice && <div className="notice" role="status"><span className="material-symbols-outlined">info</span>{notice}<button aria-label="Dismiss" onClick={() => setNotice('')}>×</button></div>}
      {view === 'overview' && <section className="view-stack">
        <div className="hero-panel"><div><p className="eyebrow">LAST 30 DAYS</p><h2 className="md-typescale-headline-small">Performance at a glance</h2><p>{data.connection ? 'Your Google Ads data is connected and report-ready.' : 'Connect Google Ads to replace the empty state with live performance.'}</p></div><div className="hero-actions">{data.connection ? <button className="filled-button" onClick={syncAds} disabled={busy}><span className="material-symbols-outlined">sync</span>Sync now</button> : <a className="filled-button" href="/api/google/connect"><span className="material-symbols-outlined">add_link</span>Connect Google Ads</a>}<button className="outlined-button" onClick={() => setView('reports')}>Create report</button></div></div>
        <div className="kpi-grid"><Kpi icon="visibility" label="Impressions" value={totals.impressions.toLocaleString()} /><Kpi icon="ads_click" label="Clicks" value={totals.clicks.toLocaleString()} /><Kpi icon="payments" label="Spend" value={`$${totals.spend.toLocaleString(undefined,{maximumFractionDigits:0})}`} /><Kpi icon="task_alt" label="Conversions" value={totals.conversions.toFixed(1)} /></div>
        <section className="content-card chart-card"><div className="card-heading"><div><p className="eyebrow">TREND</p><h2 className="md-typescale-title-large">Spend and clicks</h2></div><span className="status-chip">30 days</span></div>{chart.length ? <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="spend" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#6750a4" stopOpacity={0.35}/><stop offset="95%" stopColor="#6750a4" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7e0ec"/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="spend" stroke="#6750a4" strokeWidth={3} fill="url(#spend)"/></AreaChart></ResponsiveContainer></div> : <Empty icon="monitoring" title="No performance data yet" text="Connect and sync Google Ads to populate your trend chart." />}</section>
      </section>}
      {view === 'clients' && <section className="two-column"><section className="content-card"><div className="card-heading"><div><p className="eyebrow">CLIENT ROSTER</p><h2 className="md-typescale-title-large">Your clients</h2></div><span className="count-badge">{data.clients.length}</span></div>{data.clients.length ? <div className="list">{data.clients.map(client => <article className="list-row" key={client.id}><span className="client-logo">{client.name.slice(0,2).toUpperCase()}</span><div><strong>{client.name}</strong><small>{client.email || 'No recipient email'}</small></div><span className="status-chip">{client.status}</span></article>)}</div> : <Empty icon="group_add" title="Add your first client" text="Clients organize ad accounts, reports, recipients, and schedules." />}</section><form className="content-card form-card" onSubmit={createClient}><p className="eyebrow">NEW CLIENT</p><h2 className="md-typescale-title-large">Client details</h2><label>Client name<input name="name" required minLength={2} placeholder="Northstar Coffee" /></label><label>Report recipient<input name="email" type="email" placeholder="marketing@client.com" /></label><button className="filled-button" disabled={busy}>Add client</button></form></section>}
      {view === 'campaigns' && <section className="content-card"><div className="card-heading"><div><p className="eyebrow">GOOGLE ADS</p><h2 className="md-typescale-title-large">Campaign performance</h2></div>{data.connection && <button className="outlined-button" onClick={syncAds} disabled={busy}>Sync</button>}</div>{campaigns.length ? <div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Clicks</th><th>Spend</th><th>Conversions</th></tr></thead><tbody>{campaigns.map(c => <tr key={c.name}><td>{c.name}</td><td>{c.clicks.toLocaleString()}</td><td>${c.spend.toFixed(2)}</td><td>{c.conversions.toFixed(1)}</td></tr>)}</tbody></table></div> : <Empty icon="ads_click" title="Campaigns will appear here" text="Connect Google Ads and run your first sync." />}</section>}
      {view === 'reports' && <section className="two-column"><section className="content-card"><div className="card-heading"><div><p className="eyebrow">REPORT LIBRARY</p><h2 className="md-typescale-title-large">Generated PDFs</h2></div><span className="count-badge">{data.reports.length}</span></div>{data.reports.length ? <div className="list">{data.reports.map(report => <article className="list-row" key={report.id}><span className="report-icon material-symbols-outlined">picture_as_pdf</span><div><strong>{report.name}</strong><small>{report.period_start} — {report.period_end}</small></div>{report.status === 'ready' ? <a className="icon-button" aria-label={`Download ${report.name}`} href={`/api/reports/${report.id}/download`}><span className="material-symbols-outlined">download</span></a> : <span className="status-chip">{report.status}</span>}</article>)}</div> : <Empty icon="description" title="No reports generated" text="Create an immutable, branded PDF from synced campaign data." />}</section><form className="content-card form-card" onSubmit={generateReport}><p className="eyebrow">CREATE REPORT</p><h2 className="md-typescale-title-large">Reporting period</h2><label>Client<select name="clientId" required defaultValue=""><option value="" disabled>Select client</option>{data.clients.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Ad account<select name="accountId" required defaultValue=""><option value="" disabled>Select account</option>{data.accounts.map(a => <option value={a.id} key={a.id}>{a.descriptive_name}</option>)}</select></label><div className="date-row"><label>Start<input type="date" name="start" required /></label><label>End<input type="date" name="end" required /></label></div><button className="filled-button" disabled={busy || !data.clients.length || !data.accounts.length}>Generate PDF</button></form></section>}
      {view === 'settings' && <section className="settings-grid"><section className="content-card"><p className="eyebrow">CONNECTION</p><h2 className="md-typescale-title-large">Google Ads</h2><div className="setting-status"><span className={data.connection ? 'connection-dot connected' : 'connection-dot'}></span><div><strong>{data.connection ? 'Connected' : 'Not connected'}</strong><small>{data.connection ? `Authorized ${new Date(data.connection.connected_at).toLocaleDateString()}` : 'OAuth with read-only reporting access'}</small></div></div>{data.connection ? <button className="outlined-button" onClick={syncAds}>Sync account</button> : <a className="filled-button" href="/api/google/connect">Connect Google Ads</a>}</section><section className="content-card"><p className="eyebrow">SECURITY</p><h2 className="md-typescale-title-large">Data protection</h2><ul className="security-list"><li><span className="material-symbols-outlined">verified_user</span>Tenant-isolated Supabase RLS</li><li><span className="material-symbols-outlined">key</span>AES-256 encrypted refresh tokens</li><li><span className="material-symbols-outlined">lock</span>Private report storage</li></ul><button className="text-button danger" onClick={signOut}>Sign out</button></section></section>}
    </main>
    <nav className="bottom-nav" aria-label="Mobile navigation">{nav.slice(0,4).map(([id,icon,label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><span className="material-symbols-outlined">{icon}</span><small>{label}</small></button>)}</nav>
  </div>
}
function Kpi({ icon, label, value }: { icon: string; label: string; value: string }) { return <article className="kpi-card"><span className="kpi-icon material-symbols-outlined">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article> }
function Empty({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="empty-state"><span className="material-symbols-outlined">{icon}</span><h3>{title}</h3><p>{text}</p></div> }
