import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

export type ReportSnapshot = { agency: string; client: string; period: string; currency: string; impressions: number; clicks: number; spend: number; conversions: number; campaigns: Array<{ name: string; impressions: number; clicks: number; spend: number; conversions: number }>; delivery?: { source: string; account: string; lastSyncedAt: string | null; generatedAt: string; version: number } }

export async function createReportPdf(snapshot: ReportSnapshot) {
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([612, 792])
  const regular = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const purple = rgb(0.4, 0.31, 0.64)
  page.drawRectangle({ x: 0, y: 700, width: 612, height: 92, color: purple })
  page.drawText(snapshot.agency, { x: 44, y: 756, size: 11, font: bold, color: rgb(1, 1, 1) })
  page.drawText('GOOGLE ADS PERFORMANCE REPORT', { x: 44, y: 724, size: 22, font: bold, color: rgb(1, 1, 1) })
  page.drawText(`${snapshot.client}  |  ${snapshot.period}`, { x: 44, y: 672, size: 14, font: bold })
  const cards = [
    ['Impressions', snapshot.impressions.toLocaleString()], ['Clicks', snapshot.clicks.toLocaleString()],
    ['Spend', new Intl.NumberFormat('en-US', { style: 'currency', currency: snapshot.currency }).format(snapshot.spend)], ['Conversions', snapshot.conversions.toFixed(1)],
  ]
  cards.forEach(([label, value], i) => { const x = 44 + (i % 2) * 260; const y = 602 - Math.floor(i / 2) * 82; page.drawRectangle({ x, y, width: 236, height: 64, color: rgb(0.965, 0.95, 0.98) }); page.drawText(label, { x: x + 16, y: y + 42, size: 9, font: regular, color: rgb(0.3, 0.27, 0.32) }); page.drawText(value, { x: x + 16, y: y + 16, size: 18, font: bold }) })
  page.drawText('Campaign performance', { x: 44, y: 418, size: 16, font: bold })
  let y = 390
  for (const campaign of snapshot.campaigns.slice(0, 9)) { page.drawText(campaign.name.slice(0, 34), { x: 44, y, size: 10, font: regular }); page.drawText(`${campaign.clicks.toLocaleString()} clicks`, { x: 310, y, size: 10, font: regular }); page.drawText(new Intl.NumberFormat('en-US', { style: 'currency', currency: snapshot.currency }).format(campaign.spend), { x: 470, y, size: 10, font: bold }); y -= 28; page.drawLine({ start: { x: 44, y: y + 12 }, end: { x: 568, y: y + 12 }, thickness: 0.5, color: rgb(0.8, 0.78, 0.82) }) }
  page.drawText('Generated by AdPulse Reports', { x: 44, y: 34, size: 8, font: regular, color: rgb(0.4, 0.38, 0.42) })
  return pdf.save()
}
